import pytest
import os
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from app.main import app
from app.db.session import Base, get_db
from app.core.auth import create_access_token
from app.db.models import User, Document, ChatMessage

SQLALCHEMY_DATABASE_URL = "sqlite:///./test_fix.db"
engine = create_engine(SQLALCHEMY_DATABASE_URL, connect_args={"check_same_thread": False})
TestingSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

@pytest.fixture(scope="module")
def setup_db():
    Base.metadata.create_all(bind=engine)
    yield
    Base.metadata.drop_all(bind=engine)
    engine.dispose()
    if os.path.exists("./test_fix.db"):
        try:
            os.remove("./test_fix.db")
        except Exception:
            pass

@pytest.fixture
def db_session(setup_db):
    db = TestingSessionLocal()
    try:
        yield db
    finally:
        db.close()

@pytest.fixture
def client(db_session):
    def override_get_db():
        try:
            yield db_session
        finally:
            pass
    app.dependency_overrides[get_db] = override_get_db
    yield TestClient(app)
    del app.dependency_overrides[get_db]

@pytest.fixture
def auth_user(db_session, client):
    user = db_session.query(User).filter_by(email="test_fix@example.com").first()
    if not user:
        user = User(email="test_fix@example.com", hashed_password="hashed_pw", full_name="Test Fix")
        db_session.add(user)
        db_session.commit()
    token = create_access_token({"sub": str(user.id)})
    return {"user": user, "token": token}


def test_reopen_csv_restores_ai_insights(client, auth_user, db_session):
    # 1. Create a document with existing AI insights
    doc = Document(
        user_id=auth_user["user"].id,
        original_filename="data.csv",
        saved_filename="fakeuuid_data.csv",
        file_type="CSV",
        ai_insights="Existing test insights here."
    )
    db_session.add(doc)
    db_session.commit()
    
    # Mock settings.upload_dir_path to point to a temporary test file if analyze needs to read it
    import pandas as pd
    from app.core.config import settings
    
    test_csv = settings.upload_dir_path / doc.saved_filename
    test_csv.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame({"A": [1, 2, 3]}).to_csv(test_csv, index=False)
    
    # 2. Call /analyze/
    res = client.post("/analyze/", json={"saved_filename": doc.saved_filename}, headers={"Authorization": f"Bearer {auth_user['token']}"})
    assert res.status_code == 200
    data = res.json()
    
    # 3. Check if ai_insights is in the response
    assert data["ai_insights"] == "Existing test insights here."
    
    test_csv.unlink()


def test_ai_insights_endpoint_saves_to_document(client, auth_user, db_session):
    # Ensure POST /ai/insights/ saves insights to Document
    doc = Document(
        user_id=auth_user["user"].id,
        original_filename="data2.csv",
        saved_filename="fakeuuid_data2.csv",
        file_type="CSV",
    )
    db_session.add(doc)
    db_session.commit()
    
    # Mock LLM properly via patch
    from unittest.mock import patch
    with patch("app.api.insights.generate_insights") as mock_gen:
        mock_gen.return_value = {"status": "success", "insights": "Generated by Mock LLM", "model": "mock"}
        
        res = client.post(
            "/ai/insights/",
            json={"saved_filename": doc.saved_filename, "analysis": {"status": "success"}},
            headers={"Authorization": f"Bearer {auth_user['token']}"}
        )
    
    assert res.status_code == 200
    assert res.json()["insights"] == "Generated by Mock LLM"
    
    db_session.refresh(doc)
    assert doc.ai_insights == "Generated by Mock LLM"


def test_chart_generation_allows_four_charts():
    # Provide a dataset with many columns and verify that _generate_chart_data can return up to 4 charts
    import pandas as pd
    from app.services.analysis import analyze_dataframe
    
    # Generate data with enough variance for multiple fallback charts
    df = pd.DataFrame({
        "Category1": ["A", "A", "B", "B", "C", "C", "A", "B"] * 2,
        "Category2": ["X", "Y", "X", "Y", "X", "Y", "X", "Y"] * 2,
        "Category3": ["P", "Q", "R", "P", "Q", "R", "P", "Q"] * 2,
        "Metric1": [10, 20, 15, 25, 10, 30, 20, 25] * 2,
        "Metric2": [5, 10, 8, 12, 6, 15, 11, 13] * 2,
    })
    
    res = analyze_dataframe(df, "test.csv", "CSV")
    assert res["status"] == "success"
    charts = res["chart_data"]
    
    assert len(charts) == 4
